services:
  trips-microservice:
    build: ./trips
    container_name: trips-microservice
    ports:
      - "5001:5001"
    volumes:
      - ./trips:/app # pushes changes to the container without the need to restart docker compose
    #  - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://trips-db:27017/trips_db
    depends_on:
      - trips-db

  trips-db:
    image: mongo:latest
    container_name: trips-db
    environment:
      - MONGO_INITDB_DATABASE=trips_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    depends_on:
      - trips-microservice

volumes:
  mongo-data:
