services:
  # --- Trips Service ---
  - type: web
    name: trips-microservice
    runtime: docker
    region: frankfurt  
    plan: free
    dockerContext: ./trips   
    envVars:
      - key: PORT
        value: 5003
      - key: MONGO_URI
        sync: false               # "sync: false" means you enter it in the dashboard, not here.

  # --- Frontend Service ---
  # --- Frontend Service ---
  - type: web
    name: frontend-microservice
    runtime: docker
    region: frankfurt
    plan: free
    dockerContext: .
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: trips-microservice
          envVarKey: RENDER_EXTERNAL_URL
      - key: INTERNAL_API_URL
        fromService:
          type: web
          name: trips-microservice
          envVarKey: RENDER_EXTERNAL_URL
